### ISSUE TITLE
Fix Format Specifier error in logging 

### ISSUE THREAD

**Issue by kittylyst** [RedHatInsights/insights-runtimes-inventory#110]
Currently, errors of the type:

2023-09-28 21:28:35,421 WARN  [com.red.clo.com.clo.con.ClowderConfigSource] (main) Endpoint 'sources-api-svc' is using the old format. Please move to the new one: [Endpoint].[url|trust-store-path|trust-store-password|trust-store-type]
LogManager error of type FORMAT_FAILURE: Formatting error
java.util.MissingFormatArgumentException: Format specifier '%1s'
	at java.base/java.util.Formatter.format(Formatter.java:2688)
	at java.base/java.util.Formatter.format(Formatter.java:2625)
	at java.base/java.lang.String.format(String.java:4145)
	at org.jboss.logmanager.ExtFormatter.formatMessagePrintf(ExtFormatter.java:118)
	at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:65)

This should be fixed and move to new format.

**Comment by ebaron** [comment]
I traced the cause of the bug formatting error to a log message in clowder-quarkus-config-source. I filed a PR to fix it: https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/177
